### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by archaik** [fvcproductions/customize-icons#1]
Hi, thank you for this. When I try and run 'ChangeIcons.command', I get this error. I believe I've put everything in the right place, and am using correct syntax.

You'll be prompted once to enter you administrator password.
~/Desktop/ChangeIcons.command:37:in `read': No such file or directory @ rb_sysopen - .set_icons/icon_data.json (Errno::ENOENT)
    from ~/Desktop/ChangeIcons.command:37:in`block in <main>'
    from ~/Desktop/ChangeIcons.command:35:in `chdir'
    from ~/Desktop/ChangeIcons.command:35:in`<main>'

**Comment by FrancesCoronel** [comment]
**Hey there!** 

Did you try revealing the hidden files in Finder to see if there is a folder called `.set_icon` with a file inside it called `set_data.json`?

You would show all hidden files by executing the following commands:

``` bash
$ defaults write com.apple.finder AppleShowAllFiles YES
$ killall Finder
```

Once you do that and refresh your Finder window, you should see that hidden folder with the file.

Make sure that hidden folder is in the same directory as the `icn` files you want to use and that those are properly listed in the `set_data.json` file. 

If that still doesn't work, then please download the ZIP file again using [https://github.com/fvcproductions/customize-icons/archive/v1.0.zip](https://github.com/fvcproductions/customize-icons/archive/v1.0.zip).

Hope this helps! 😄
